name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: check dir
      run: ls -l /home/runner/.katalon/7.5.5/Katalon_Studio_Engine_Linux_64-7.5.5/configuration/1706695262935.log
