name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Chrome
      run: |
        choco install googlechrome --version=114.0.5735.199
      shell: powershell

      - name: Download ChromeDriver
      run: |
        $chromeDriverVersion = "114.0.5735.199"
        $chromeDriverUrl = "https://chromedriver.storage.googleapis.com/$chromeDriverVersion/chromedriver_win64.zip"
        Invoke-WebRequest -Uri $chromeDriverUrl -OutFile chromedriver.zip
        Expand-Archive -Path chromedriver.zip -DestinationPath $env:USERPROFILE\.wdm\chromedriver
      
    - name: Katalon Studio Github Action
      uses: katalon-studio/katalon-studio-github-action@v2
      with:
          version: '7.5.5'
          projectPath: '${{ github.workspace }}'
          args: '-noSplash -retry=0 -testSuitePath="Test Suites/Login Suite" -apiKey=${{ secrets.WEBACTIONS }} --config -webui.autoUpdateDrivers=true -browserType="Chrome"'
